qt5_5_0.diff

diff --git a/repos/libports/src/lib/qt5/patches/qt5_configuration.patch b/repos/libports/src/lib/qt5/patches/qt5_configuration.patch
--- a/repos/libports/src/lib/qt5/patches/qt5_configuration.patch
+++ b/repos/libports/src/lib/qt5/patches/qt5_configuration.patch
@@ -4,25 +4,25 @@ From: Christian Prochaska <christian.prochaska@genode-labs.com>
 
 
 ---
- qt.pro                                             |   52 +-
- qtbase/configure                                   |    6 
- qtbase/mkspecs/genode-g++/qmake.conf               |   12 +
- qtbase/mkspecs/genode-g++/qplatformdefs.h          |  112 +++++
- qtbase/src/corelib/global/qconfig-genode.h         |  425 ++++++++++++++++++++
- qtdeclarative/examples/quick/quick.pro             |    6 
- qtdeclarative/tests/tests.pro                      |    4 
+ qt.pro                                             |   56 +--
+ qtbase/configure                                   |   92 ++--
+ qtbase/mkspecs/genode-g++/qmake.conf               |   10 
+ qtbase/mkspecs/genode-g++/qplatformdefs.h          |   82 ++++
+ qtbase/src/corelib/global/qconfig-genode.h         |  426 ++++++++++++++++++++
+ qtdeclarative/tools/tools.pro                      |    3 
+ .../Tools/qmake/mkspecs/features/configure.prf     |    1 
  qtwebkit/Tools/qmake/mkspecs/features/features.prf |    6 
  qtwebkit/Tools/qmake/mkspecs/features/features.pri |    2 
- 9 files changed, 589 insertions(+), 36 deletions(-)
+ 9 files changed, 597 insertions(+), 81 deletions(-)
  create mode 100644 qtbase/mkspecs/genode-g++/qmake.conf
  create mode 100644 qtbase/mkspecs/genode-g++/qplatformdefs.h
  create mode 100644 qtbase/src/corelib/global/qconfig-genode.h
 
 diff --git a/qt.pro b/qt.pro
-index 15fd48e..73262af 100644
+index 01547d4..1ba7585 100644
 --- a/qt.pro
 +++ b/qt.pro
-@@ -58,37 +58,37 @@ ANDROID_EXTRAS =
+@@ -58,38 +58,38 @@ ANDROID_EXTRAS =
  android: ANDROID_EXTRAS = qtandroidextras
  
  addModule(qtbase)
@@ -35,26 +35,24 @@ index 15fd48e..73262af 100644
  addModule(qtsvg, qtbase)
  addModule(qtxmlpatterns, qtbase)
  addModule(qtdeclarative, qtbase, qtsvg qtxmlpatterns)
--addModule(qtquickcontrols, qtdeclarative)
+-addModule(qtquickcontrols, qtdeclarative, qtgraphicaleffects)
 -addModule(qtmultimedia, qtbase, qtdeclarative)
 -addModule(qtwinextras, qtbase, qtdeclarative qtmultimedia)
 -addModule(qtactiveqt, qtbase)
--addModule(qt3d, qtdeclarative)
 -addModule(qtsystems, qtbase, qtdeclarative)
--addModule(qtlocation, qtbase, qtsystems qtmultimedia)
+-addModule(qtlocation, qtbase, qtdeclarative qtsystems)
 -addModule(qtsensors, qtbase, qtdeclarative)
 -addModule(qtconnectivity, qtbase $$ANDROID_EXTRAS, qtdeclarative)
 -addModule(qtfeedback, qtdeclarative, qtmultimedia)
 -addModule(qtpim, qtdeclarative)
 -addModule(qtwebsockets, qtbase, qtdeclarative)
 -addModule(qtwebchannel, qtbase, qtdeclarative qtwebsockets)
-+#addModule(qtquickcontrols, qtdeclarative)
++#addModule(qtquickcontrols, qtdeclarative, qtgraphicaleffects)
 +#addModule(qtmultimedia, qtbase, qtdeclarative)
 +#addModule(qtwinextras, qtbase, qtdeclarative qtmultimedia)
 +#addModule(qtactiveqt, qtbase)
-+#addModule(qt3d, qtdeclarative)
 +#addModule(qtsystems, qtbase, qtdeclarative)
-+#addModule(qtlocation, qtbase, qtsystems qtmultimedia)
++#addModule(qtlocation, qtbase, qtdeclarative qtsystems)
 +#addModule(qtsensors, qtbase, qtdeclarative)
 +#addModule(qtconnectivity, qtbase $$ANDROID_EXTRAS, qtdeclarative)
 +#addModule(qtfeedback, qtdeclarative, qtmultimedia)
@@ -62,35 +60,40 @@ index 15fd48e..73262af 100644
 +#addModule(qtwebsockets, qtbase, qtdeclarative)
 +#addModule(qtwebchannel, qtbase, qtdeclarative qtwebsockets)
  addModule(qtwebkit, qtdeclarative, qtlocation qtmultimedia qtsensors qtwebchannel, WebKit.pro)
- addModule(qttools, qtbase, qtdeclarative qtactiveqt qtwebkit)
+-addModule(qttools, qtbase, qtdeclarative qtactiveqt qtwebkit)
++#addModule(qttools, qtbase, qtdeclarative qtactiveqt qtwebkit)
  addModule(qtwebkit-examples, qtwebkit qttools)
  addModule(qtimageformats, qtbase)
+-addModule(qt3d, qtdeclarative qtimageformats)
+-addModule(qtcanvas3d, qtdeclarative)
 -addModule(qtgraphicaleffects, qtdeclarative)
++#addModule(qt3d, qtdeclarative qtimageformats)
++#addModule(qtcanvas3d, qtdeclarative)
 +#addModule(qtgraphicaleffects, qtdeclarative)
  addModule(qtscript, qtbase, qttools)
 -addModule(qtquick1, qtscript, qtsvg qtxmlpatterns qtwebkit)
 -addModule(qtdocgallery, qtdeclarative)
--linux:!android: addModule(qtwayland, qtbase, qtdeclarative)
+-addModule(qtwayland, qtbase, qtdeclarative)
 -addModule(qtserialport, qtbase)
 -addModule(qtenginio, qtdeclarative)
--addModule(qtwebengine, qtquickcontrols, qtwebkit)
+-addModule(qtwebengine, qtquickcontrols qtwebchannel, qtwebkit qtlocation)
 -addModule(qttranslations, qttools)
 -addModule(qtdoc, qtdeclarative)
 -addModule(qtqa, qtbase)
 +#addModule(qtquick1, qtscript, qtsvg qtxmlpatterns qtwebkit)
 +#addModule(qtdocgallery, qtdeclarative)
-+#linux:!android: addModule(qtwayland, qtbase, qtdeclarative)
++#addModule(qtwayland, qtbase, qtdeclarative)
 +#addModule(qtserialport, qtbase)
 +#addModule(qtenginio, qtdeclarative)
-+#addModule(qtwebengine, qtquickcontrols, qtwebkit)
++#addModule(qtwebengine, qtquickcontrols qtwebchannel, qtwebkit qtlocation)
 +#addModule(qttranslations, qttools)
 +#addModule(qtdoc, qtdeclarative)
 +#addModule(qtqa, qtbase)
 diff --git a/qtbase/configure b/qtbase/configure
-index 6ce6753..e1872df 100755
+index 8a4c89e..7987008 100755
 --- a/qtbase/configure
 +++ b/qtbase/configure
-@@ -592,10 +592,10 @@ CFG_ZLIB=auto
+@@ -622,10 +622,10 @@ CFG_ZLIB=auto
  CFG_MTDEV=auto
  CFG_JOURNALD=no
  CFG_SQLITE=qt
@@ -103,7 +106,7 @@ index 6ce6753..e1872df 100755
  CFG_LIBJPEG=auto
  CFG_XCURSOR=runtime
  CFG_XRANDR=runtime
-@@ -688,7 +688,7 @@ CFG_GETADDRINFO=auto
+@@ -724,7 +724,7 @@ CFG_GETADDRINFO=auto
  CFG_IPV6IFNAME=auto
  CFG_GETIFADDRS=auto
  CFG_INOTIFY=auto
@@ -112,66 +115,156 @@ index 6ce6753..e1872df 100755
  CFG_RPATH=yes
  CFG_FRAMEWORK=auto
  CFG_USE_GOLD_LINKER=auto
+@@ -5179,16 +5179,16 @@ elif [ "$CFG_OPENGL" = "es2" ]; then
+         echo " ${XQMAKESPEC}."
+         exit 1
+     fi
+-elif [ "$CFG_OPENGL" = "desktop" ]; then
+-    # Desktop OpenGL support
+-    compileTestWithPkgConfig gl unix/opengldesktop "OpenGL" OPENGL
+-    if [ $? != "0" ]; then
+-        echo "The OpenGL functionality test failed!"
+-        echo " You might need to modify the include and library search paths by editing"
+-        echo " QMAKE_INCDIR_OPENGL, QMAKE_LIBDIR_OPENGL and QMAKE_LIBS_OPENGL in"
+-        echo " ${XQMAKESPEC}."
+-        exit 1
+-    fi
++#elif [ "$CFG_OPENGL" = "desktop" ]; then
++#    # Desktop OpenGL support
++#    compileTestWithPkgConfig gl unix/opengldesktop "OpenGL" OPENGL
++#    if [ $? != "0" ]; then
++#        echo "The OpenGL functionality test failed!"
++#        echo " You might need to modify the include and library search paths by editing"
++#        echo " QMAKE_INCDIR_OPENGL, QMAKE_LIBDIR_OPENGL and QMAKE_LIBS_OPENGL in"
++#        echo " ${XQMAKESPEC}."
++#        exit 1
++#    fi
+ fi
+ 
+ # If OpenGL ES 2.0 is enabled, check for 3.0 and higher. This is used to allow
+@@ -5568,39 +5568,39 @@ else
+ fi
+ 
+ # EGL Support
+-if [ "$CFG_EGL" != "no" ]; then
+-    if [ "$CFG_EGL" = "yes" ] && [ "$CFG_OPENGL" = "no" ]; then
+-        echo "EGL support was requested but OpenGL support is disabled."
+-        echo "Either disable EGL support or enable OpenGL support."
+-        exit 101
+-    fi
+-
+-    if [ -n "$PKG_CONFIG" ] && $PKG_CONFIG --exists egl 2>/dev/null; then
+-        QMAKE_INCDIR_EGL=`$PKG_CONFIG --cflags-only-I egl 2>/dev/null | sed -e 's,^-I,,g' -e 's, -I, ,g'`
+-        QMAKE_LIBS_EGL=`$PKG_CONFIG --libs egl 2>/dev/null`
+-        QMAKE_CFLAGS_EGL=`$PKG_CONFIG --cflags egl 2>/dev/null`
+-        QMakeVar set QMAKE_INCDIR_EGL "$QMAKE_INCDIR_EGL"
+-        QMakeVar set QMAKE_LIBS_EGL "$QMAKE_LIBS_EGL"
+-        QMakeVar set QMAKE_CFLAGS_EGL "`echo " $QMAKE_CFLAGS_EGL " | sed -e 's, -I[^ ]* , ,g;s,^ ,,;s, $,,'`"
+-    fi       # detect EGL support
+-    if compileTest qpa/egl "EGL" $QMAKE_CFLAGS_EGL $QMAKE_LIBS_EGL; then
+-        CFG_EGL=yes
+-        if compileTest qpa/egl-x11 "EGL-X11" $QMAKE_CFLAGS_EGL $QMAKE_LIBS_EGL; then
+-            CFG_EGL_X=yes
+-        else
+-            CFG_EGL_X=no
+-        fi
+-    elif [ "$CFG_EGL" = "yes" ]; then
+-        echo " The EGL functionality test failed; EGL is required by some QPA plugins to manage contexts & surfaces."
+-        [ -z "$PKG_CONFIG" ] && echo " Use of pkg-config is not enabled, maybe you want to pass -force-pkg-config?"
+-        echo " You might need to modify the include and library search paths by editing"
+-        echo " QMAKE_INCDIR_EGL, QMAKE_LIBDIR_EGL and QMAKE_LIBS_EGL in ${XQMAKESPEC}."
+-        exit 1
+-    else
+-        CFG_EGL=no
+-        CFG_EGL_X=no
+-    fi
+-fi
++#if [ "$CFG_EGL" != "no" ]; then
++#    if [ "$CFG_EGL" = "yes" ] && [ "$CFG_OPENGL" = "no" ]; then
++#        echo "EGL support was requested but OpenGL support is disabled."
++#        echo "Either disable EGL support or enable OpenGL support."
++#        exit 101
++#    fi
++#
++#    if [ -n "$PKG_CONFIG" ] && $PKG_CONFIG --exists egl 2>/dev/null; then
++#        QMAKE_INCDIR_EGL=`$PKG_CONFIG --cflags-only-I egl 2>/dev/null | sed -e 's,^-I,,g' -e 's, -I, ,g'`
++#        QMAKE_LIBS_EGL=`$PKG_CONFIG --libs egl 2>/dev/null`
++#        QMAKE_CFLAGS_EGL=`$PKG_CONFIG --cflags egl 2>/dev/null`
++#        QMakeVar set QMAKE_INCDIR_EGL "$QMAKE_INCDIR_EGL"
++#        QMakeVar set QMAKE_LIBS_EGL "$QMAKE_LIBS_EGL"
++#        QMakeVar set QMAKE_CFLAGS_EGL "`echo " $QMAKE_CFLAGS_EGL " | sed -e 's, -I[^ ]* , ,g;s,^ ,,;s, $,,'`"
++#    fi       # detect EGL support
++#    if compileTest qpa/egl "EGL" $QMAKE_CFLAGS_EGL $QMAKE_LIBS_EGL; then
++#        CFG_EGL=yes
++#        if compileTest qpa/egl-x11 "EGL-X11" $QMAKE_CFLAGS_EGL $QMAKE_LIBS_EGL; then
++#            CFG_EGL_X=yes
++#        else
++#            CFG_EGL_X=no
++#        fi
++#    elif [ "$CFG_EGL" = "yes" ]; then
++#        echo " The EGL functionality test failed; EGL is required by some QPA plugins to manage contexts & surfaces."
++#        [ -z "$PKG_CONFIG" ] && echo " Use of pkg-config is not enabled, maybe you want to pass -force-pkg-config?"
++#        echo " You might need to modify the include and library search paths by editing"
++#        echo " QMAKE_INCDIR_EGL, QMAKE_LIBDIR_EGL and QMAKE_LIBS_EGL in ${XQMAKESPEC}."
++#        exit 1
++#    else
++#        CFG_EGL=no
++#        CFG_EGL_X=no
++#    fi
++#fi
+ 
+ if [ "$CFG_EGLFS" != "no" ]; then
+     if [ "$XPLATFORM_QNX" = "no" ] && [ "$CFG_OPENGL" != "no" ]; then
 diff --git a/qtbase/mkspecs/genode-g++/qmake.conf b/qtbase/mkspecs/genode-g++/qmake.conf
 new file mode 100644
-index 0000000..f99671f
+index 0000000..734ae5c
 --- /dev/null
 +++ b/qtbase/mkspecs/genode-g++/qmake.conf
-@@ -0,0 +1,12 @@
+@@ -0,0 +1,10 @@
 +#
 +# qmake configuration for genode-g++
 +#
 +
 +MAKEFILE_GENERATOR	= UNIX
-+CONFIG += incremental gdb_dwarf_index
-+QMAKE_INCREMENTAL_STYLE = sublib
 +
-+include(../common/linux.conf)
++include(../common/unix.conf)
 +include(../common/gcc-base-unix.conf)
 +include(../common/g++-unix.conf)
 +load(qt_config)
 diff --git a/qtbase/mkspecs/genode-g++/qplatformdefs.h b/qtbase/mkspecs/genode-g++/qplatformdefs.h
 new file mode 100644
-index 0000000..4d2c580
+index 0000000..d4d67b0
 --- /dev/null
 +++ b/qtbase/mkspecs/genode-g++/qplatformdefs.h
-@@ -0,0 +1,112 @@
+@@ -0,0 +1,82 @@
 +/****************************************************************************
 +**
-+** Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
-+** Contact: http://www.qt-project.org/legal
++** Copyright (C) 2015 The Qt Company Ltd.
++** Contact: http://www.qt.io/licensing/
 +**
 +** This file is part of the qmake spec of the Qt Toolkit.
 +**
-+** $QT_BEGIN_LICENSE:LGPL$
++** $QT_BEGIN_LICENSE:LGPL21$
 +** Commercial License Usage
 +** Licensees holding valid commercial Qt licenses may use this file in
 +** accordance with the commercial license agreement provided with the
 +** Software or, alternatively, in accordance with the terms contained in
-+** a written agreement between you and Digia.  For licensing terms and
-+** conditions see http://qt.digia.com/licensing.  For further information
-+** use the contact form at http://qt.digia.com/contact-us.
++** a written agreement between you and The Qt Company. For licensing terms
++** and conditions see http://www.qt.io/terms-conditions. For further
++** information use the contact form at http://www.qt.io/contact-us.
 +**
 +** GNU Lesser General Public License Usage
 +** Alternatively, this file may be used under the terms of the GNU Lesser
-+** General Public License version 2.1 as published by the Free Software
-+** Foundation and appearing in the file LICENSE.LGPL included in the
-+** packaging of this file.  Please review the following information to
-+** ensure the GNU Lesser General Public License version 2.1 requirements
-+** will be met: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html.
++** General Public License version 2.1 or version 3 as published by the Free
++** Software Foundation and appearing in the file LICENSE.LGPLv21 and
++** LICENSE.LGPLv3 included in the packaging of this file. Please review the
++** following information to ensure the GNU Lesser General Public License
++** requirements will be met: https://www.gnu.org/licenses/lgpl.html and
++** http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html.
 +**
-+** In addition, as a special exception, Digia gives you certain additional
-+** rights.  These rights are described in the Digia Qt LGPL Exception
++** As a special exception, The Qt Company gives you certain additional
++** rights. These rights are described in The Qt Company LGPL Exception
 +** version 1.1, included in the file LGPL_EXCEPTION.txt in this package.
-+**
-+** GNU General Public License Usage
-+** Alternatively, this file may be used under the terms of the GNU
-+** General Public License version 3.0 as published by the Free Software
-+** Foundation and appearing in the file LICENSE.GPL included in the
-+** packaging of this file.  Please review the following information to
-+** ensure the GNU General Public License version 3.0 requirements will be
-+** met: http://www.gnu.org/copyleft/gpl.html.
-+**
 +**
 +** $QT_END_LICENSE$
 +**
@@ -186,28 +279,21 @@ index 0000000..4d2c580
 +
 +// Set any POSIX/XOPEN defines at the top of this file to turn on specific APIs
 +
-+// 1) need to reset default environment if _BSD_SOURCE is defined
-+// 2) need to specify POSIX thread interfaces explicitly in glibc 2.0
-+// 3) it seems older glibc need this to include the X/Open stuff
-+#ifndef _GNU_SOURCE
-+#  define _GNU_SOURCE
-+#endif
-+
 +#include <unistd.h>
 +
 +
 +// We are hot - unistd.h should have turned on the specific APIs we requested
 +
-+#ifndef Q_OS_GENODE
-+#include <features.h>
-+#endif
++
 +#include <pthread.h>
 +#include <dirent.h>
 +#include <fcntl.h>
 +#include <grp.h>
 +#include <pwd.h>
 +#include <signal.h>
++#include <dlfcn.h>
 +
++#include <sys/param.h>
 +#include <sys/types.h>
 +#include <sys/ioctl.h>
 +#include <sys/ipc.h>
@@ -219,41 +305,26 @@ index 0000000..4d2c580
 +#include <sys/stat.h>
 +#include <sys/wait.h>
 +#include <netinet/in.h>
-+#ifdef Q_OS_GENODE
-+#define QT_NO_IPV6IFNAME
-+#endif
 +#ifndef QT_NO_IPV6IFNAME
 +#include <net/if.h>
 +#endif
 +
-+#define QT_USE_XOPEN_LFS_EXTENSIONS
 +#include "../common/posix/qplatformdefs.h"
 +
-+#ifdef Q_OS_GENODE
 +#undef QT_OPEN_LARGEFILE
++
 +#define QT_OPEN_LARGEFILE 0
-+#endif
 +
-+#undef QT_SOCKLEN_T
-+
-+#if (defined(__GLIBC__) && (__GLIBC__ >= 2)) || defined(Q_OS_GENODE)
-+#define QT_SOCKLEN_T            socklen_t
-+#else
-+#define QT_SOCKLEN_T            int
-+#endif
-+
-+#if defined(_XOPEN_SOURCE) && (_XOPEN_SOURCE >= 500)
 +#define QT_SNPRINTF		::snprintf
 +#define QT_VSNPRINTF		::vsnprintf
-+#endif
 +
 +#endif // QPLATFORMDEFS_H
 diff --git a/qtbase/src/corelib/global/qconfig-genode.h b/qtbase/src/corelib/global/qconfig-genode.h
 new file mode 100644
-index 0000000..8262e36
+index 0000000..56a0b73
 --- /dev/null
 +++ b/qtbase/src/corelib/global/qconfig-genode.h
-@@ -0,0 +1,425 @@
+@@ -0,0 +1,426 @@
 +/* Data structures */
 +//#ifndef QT_NO_TEXTDATE
 +//#  define QT_NO_TEXTDATE
@@ -472,10 +543,11 @@ index 0000000..8262e36
 +#ifndef QT_NO_FTP
 +#  define QT_NO_FTP
 +#endif
++
++/* Added for Genode */
 +#ifndef QT_NO_NETWORKINTERFACE
 +#  define QT_NO_NETWORKINTERFACE
 +#endif
-+
 +
 +/* Painting */
 +//#ifndef QT_NO_COLORNAMES
@@ -679,40 +751,36 @@ index 0000000..8262e36
 +//#ifndef QT_NO_VALIDATOR
 +//#  define QT_NO_VALIDATOR
 +//#endif
-diff --git a/qtdeclarative/examples/quick/quick.pro b/qtdeclarative/examples/quick/quick.pro
-index a412c53..cfd014a 100644
---- a/qtdeclarative/examples/quick/quick.pro
-+++ b/qtdeclarative/examples/quick/quick.pro
-@@ -13,7 +13,6 @@ SUBDIRS =   quick-accessibility \
-             positioners \
-             righttoleft \
-             scenegraph \
--            shadereffects \
-             text \
-             threading \
-             touchinteraction \
-@@ -31,5 +30,10 @@ qtHaveModule(widgets) {
-     qtHaveModule(quickwidgets): SUBDIRS += quickwidgets
- }
+diff --git a/qtdeclarative/tools/tools.pro b/qtdeclarative/tools/tools.pro
+index b2e9e27..efeb801 100644
+--- a/qtdeclarative/tools/tools.pro
++++ b/qtdeclarative/tools/tools.pro
+@@ -9,10 +9,9 @@ qmlimportscanner.CONFIG = host_build
+ !android|android_app {
+     SUBDIRS += \
+         qml \
+-        qmlprofiler \
+         qmllint
+     qtHaveModule(quick) {
+-        !static: SUBDIRS += qmlscene qmlplugindump
++        !static: SUBDIRS += qmlscene
+         qtHaveModule(widgets): SUBDIRS += qmleasing
+     }
+     qtHaveModule(qmltest): SUBDIRS += qmltestrunner
+diff --git a/qtwebkit/Tools/qmake/mkspecs/features/configure.prf b/qtwebkit/Tools/qmake/mkspecs/features/configure.prf
+index 0df5ee4..03ed243 100644
+--- a/qtwebkit/Tools/qmake/mkspecs/features/configure.prf
++++ b/qtwebkit/Tools/qmake/mkspecs/features/configure.prf
+@@ -49,7 +49,6 @@ defineTest(runConfigure) {
  
-+# OpenGL dependent examples
-+qtHaveModule(opengl) {
-+	SUBDIRS += shadereffects
-+}
-+
- EXAMPLE_FILES = \
-     shared
-diff --git a/qtdeclarative/tests/tests.pro b/qtdeclarative/tests/tests.pro
-index 85e4f3a..9aa752b 100644
---- a/qtdeclarative/tests/tests.pro
-+++ b/qtdeclarative/tests/tests.pro
-@@ -1,2 +1,2 @@
--TEMPLATE = subdirs
--SUBDIRS +=  auto
-+#TEMPLATE = subdirs
-+#SUBDIRS +=  auto
+     WEBKIT_CONFIG += \
+         build_webkit1 \
+-        build_webkit2 \
+         build_tests \
+         $$WEBKIT_TOOLS_CONFIG
+ 
 diff --git a/qtwebkit/Tools/qmake/mkspecs/features/features.prf b/qtwebkit/Tools/qmake/mkspecs/features/features.prf
-index ef1d5d7..002890d 100644
+index 7b0b49d..57adfd2 100644
 --- a/qtwebkit/Tools/qmake/mkspecs/features/features.prf
 +++ b/qtwebkit/Tools/qmake/mkspecs/features/features.prf
 @@ -42,8 +42,8 @@ defineTest(detectFeatures) {
